service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${self:custom.extra.REGION}
  apiName: ${self:custom.extra.API_NAME}
  timeout: 300 #Default Lambda timeout
  memorySize: 512 #Default Lambda Memory Size
  versionFunctions: false # No functions versioning
  #role: arn:aws:iam::#{AWS::AccountId}:role/existing-role
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
      - .test/**
      - deploy-policy.json
      - docker-compose.yml
      - Dockerfile
      - package-lock.json
      - README.md
  iamRoleStatements: # Permissions for all of your functions can be set here
  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: 'arn:aws:dynamodb:${self:custom.extra.REGION}:*:*'
  - Effect: Allow
    Action: # Gives permission to Lambda execution
      - lambda:InvokeFunction
      - lambda:InvokeAsync
    Resource: "*"
  environment: #Global Environment variables
    ${file(./configs/${opt:stage, 'prod'}.yml)}

  # - Effect: Allow
  #   Action: # Gives permission to SQS
  #     - sqs:DeleteMessage
  #     - sqs:ReceiveMessage
  #     - sqs:SendMessage
  #   Resource: arn:aws:sqs:*:*:*

custom:
  region: ${self:provider.region}
  stage: ${self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  config: ${self:custom.prefix}-config
  sns-logs: ${self:custom.prefix}-trigger-logs
  sqs-logs: ${self:custom.prefix}-messages-logs
  bucketName: ${self:custom.extra.BUCKET_NAME}
  extra: ${file(./configs/${opt:stage, 'prod'}.yml)}
  lambda-name: ${self:custom.extra.LAMBDA_NAME}
  lambda-description: ${self:custom.extra.LAMBDA_DESCRIPTION}

  serverless-offline:
    host: '0.0.0.0'
  splitStacks:
    perFunction: true
    perType: true
  # serverless-offline-sqs-esmq:
  #   apiVersion: '2012-11-05'
  #   endpoint: http://sqs:9324
  #   region: sa-east-1
  #   accessKeyId: root
  #   secretAccessKey: root
  dynamodb:
    stages:
      - local
      - prod
      - dev
    start:
      host: "dynamo"
      port: 8000
      inMemory: false
      migrate: true
      noStart: true
  # add resources
  additionalStacks:
    permanent:
      Resources:
        DemoBucketUpload:
          Type: AWS::S3::Bucket
          Properties:
              BucketName: ${self:custom.bucketName}
        #DynamoDB Books Table
        DynamoDBCatalog:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: ${self:custom.extra.DYNAMO_TABLE}
            AttributeDefinitions:
              - AttributeName: hashkey
                AttributeType: S
            KeySchema:
              - AttributeName: hashkey
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST

        # SQS Queue to Update DynamoDB
        # BooksQueueExample:
        #   Type: AWS::SQS::Queue
        #   Properties:
        #     QueueName: ${self:custom.sqs-logs}
        #     MessageRetentionPeriod: 1209600
        #     VisibilityTimeout: 60
  documentation:
    # this is general info about the API
    api:
      info:
        version: '2'
        title: Example API
        description: Some example API
        termsOfService: https://www.google.com
        contact:
          name: The contact person
          url: https://www.serverless.com/framework
          email: some-fake@email.com
        license:
          name: The license
          url: https://www.github.com
      tags:
        -
          name: Tag1
          description: The first tag
        -
          name: Tag2
          description: That other tag that we all love
    # Now we describe all the models that we use
    models:
      -
        name: books
        contentType: "application/json"
        schema:
          type: array
          items:
            type: string
      -
        name: ErrorResponse
        contentType: "application/json"
        schema:
          type: object
          properties:
            message:
              type: string
            statusCode:
              type: number
  commonModelSchemaFragments:
    # defining common fragments means you can reference them with a single line
    MethodResponse400Json:
      statusCode: '400'
      responseModels:
        "application/json": ErrorResponse

plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  # - serverless-offline-sqs-esmq
  - serverless-offline
  - serverless-aws-documentation
  - serverless-plugin-additional-stacks

functions: ${file(serverless-dynamic.js)}
